/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScreenplayId = IDL.Text;
export const Timestamp = IDL.Int;
export const Screenplay = IDL.Record({
  'id' : ScreenplayId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'language' : IDL.Text,
});
export const CharacterVoiceSetting = IDL.Record({
  'character' : IDL.Text,
  'rate' : IDL.Float64,
  'language' : IDL.Text,
  'voiceUri' : IDL.Text,
  'providerType' : IDL.Opt(IDL.Text),
  'pitch' : IDL.Float64,
});
export const ScreenplaySummary = IDL.Record({
  'id' : ScreenplayId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'language' : IDL.Text,
});

export const idlService = IDL.Service({
  'addScreenplay' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ScreenplayId, 'err' : IDL.Text })],
      [],
    ),
  'deleteScreenplay' : IDL.Func(
      [ScreenplayId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getActiveProvider' : IDL.Func([ScreenplayId], [IDL.Text], ['query']),
  'getScreenplay' : IDL.Func([ScreenplayId], [IDL.Opt(Screenplay)], ['query']),
  'getVoiceSettings' : IDL.Func(
      [ScreenplayId],
      [IDL.Vec(CharacterVoiceSetting)],
      ['query'],
    ),
  'listScreenplays' : IDL.Func([], [IDL.Vec(ScreenplaySummary)], ['query']),
  'saveVoiceSettings' : IDL.Func(
      [ScreenplayId, IDL.Vec(CharacterVoiceSetting), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScreenplayId = IDL.Text;
  const Timestamp = IDL.Int;
  const Screenplay = IDL.Record({
    'id' : ScreenplayId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'language' : IDL.Text,
  });
  const CharacterVoiceSetting = IDL.Record({
    'character' : IDL.Text,
    'rate' : IDL.Float64,
    'language' : IDL.Text,
    'voiceUri' : IDL.Text,
    'providerType' : IDL.Opt(IDL.Text),
    'pitch' : IDL.Float64,
  });
  const ScreenplaySummary = IDL.Record({
    'id' : ScreenplayId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'language' : IDL.Text,
  });
  
  return IDL.Service({
    'addScreenplay' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ScreenplayId, 'err' : IDL.Text })],
        [],
      ),
    'deleteScreenplay' : IDL.Func(
        [ScreenplayId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getActiveProvider' : IDL.Func([ScreenplayId], [IDL.Text], ['query']),
    'getScreenplay' : IDL.Func(
        [ScreenplayId],
        [IDL.Opt(Screenplay)],
        ['query'],
      ),
    'getVoiceSettings' : IDL.Func(
        [ScreenplayId],
        [IDL.Vec(CharacterVoiceSetting)],
        ['query'],
      ),
    'listScreenplays' : IDL.Func([], [IDL.Vec(ScreenplaySummary)], ['query']),
    'saveVoiceSettings' : IDL.Func(
        [ScreenplayId, IDL.Vec(CharacterVoiceSetting), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };