/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CharacterVoiceSetting {
  'character' : string,
  'rate' : number,
  'language' : string,
  'voiceUri' : string,
  'providerType' : [] | [string],
  'pitch' : number,
}
export interface Screenplay {
  'id' : ScreenplayId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'language' : string,
}
export type ScreenplayId = string;
export interface ScreenplaySummary {
  'id' : ScreenplayId,
  'title' : string,
  'createdAt' : Timestamp,
  'language' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addScreenplay' : ActorMethod<
    [string, string, string],
    { 'ok' : ScreenplayId } |
      { 'err' : string }
  >,
  'deleteScreenplay' : ActorMethod<
    [ScreenplayId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getActiveProvider' : ActorMethod<[ScreenplayId], string>,
  'getScreenplay' : ActorMethod<[ScreenplayId], [] | [Screenplay]>,
  'getVoiceSettings' : ActorMethod<
    [ScreenplayId],
    Array<CharacterVoiceSetting>
  >,
  'listScreenplays' : ActorMethod<[], Array<ScreenplaySummary>>,
  'saveVoiceSettings' : ActorMethod<
    [ScreenplayId, Array<CharacterVoiceSetting>, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];